---

- name: symlink latest release
  file:
    path={{ sites_directory }}/{{ site_name }}/application/current
    src={{ sites_directory }}/{{ site_name }}/application/releases/{{ timestamp.stdout }}/{{ drupal_root }}
    state=link
  tags:
    - revert
    - release

- name: symlink config directory
  become: yes
  become_method: sudo
  file:
    path={{ sites_directory }}/{{ site_name }}/config
    src={{ sites_directory }}/{{ site_name }}/application/releases/{{ timestamp.stdout }}/config
    state=link
  tags:
    - revert
    - release

- name: symlink vendor directory
  become: yes
  become_method: sudo
  file:
    path={{ sites_directory }}/{{ site_name }}/vendor
    src={{ sites_directory }}/{{ site_name }}/application/releases/{{ timestamp.stdout }}/vendor
    state=link
  tags:
    - revert
    - release

- name: remove files directory if files are symlinked
  when: files_symlink_path is defined
  file:
    path={{ sites_directory }}/{{ site_name }}/application/shared/{{ item.name }}/files
    state=absent
  with_items: "{{ site_roots }}"
  tags:
    - deploy
    - release

- name: symlink files directory
  when: files_symlink_path is defined
  file:
    path={{ sites_directory }}/{{ site_name }}/application/shared/{{ item.name }}/files
    src={{ files_symlink_path }}
    force=yes
    state=link
  with_items: "{{ site_roots }}"
  tags:
    - deploy
    - release

- name: remove oldest releases
  become: yes
  become_method: sudo
  shell:
    ls | sort -r | tail -n +{{ max_releases + 1 }} | xargs rm -rf
    chdir={{ sites_directory }}/{{ site_name }}/application/releases
  tags:
    - release
